# Generated by Django 3.0 on 2019-12-11 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appartenir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_categorie', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_matricule', models.IntegerField()),
                ('niveau', models.CharField(max_length=255)),
                ('parcours', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Individu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('cin', models.CharField(blank=True, max_length=255)),
                ('faceId', models.ImageField(upload_to='photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_matiere', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_responsable', models.CharField(max_length=255)),
                ('individu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='presence.Individu')),
            ],
        ),
        migrations.CreateModel(
            name='GroupeParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_groupe_participant', models.CharField(max_length=255)),
                ('membres', models.ManyToManyField(related_name='_groupeparticipant_membres_+', through='presence.Appartenir', to='presence.Etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presence.Categorie')),
                ('matiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='presence.Matiere')),
                ('presences', models.ManyToManyField(related_name='evenements', to='presence.Etudiant')),
            ],
        ),
        migrations.AddField(
            model_name='etudiant',
            name='individu',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='presence.Individu'),
        ),
        migrations.AddField(
            model_name='appartenir',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presence.Etudiant'),
        ),
        migrations.AddField(
            model_name='appartenir',
            name='groupe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presence.GroupeParticipant'),
        ),
    ]
