# Generated by Django 3.0 on 2019-12-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appartenir',
            name='numero',
            field=models.IntegerField(blank=True),
        ),
    ]
