# Generated by Django 3.0 on 2019-12-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0002_auto_20191211_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appartenir',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
