# Generated by Django 3.0 on 2019-12-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0003_auto_20191211_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='responsables',
            field=models.ManyToManyField(related_name='evenements', to='presence.Responsable'),
        ),
    ]
