# Generated by Django 3.0 on 2019-12-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0005_auto_20191211_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='presences',
            field=models.ManyToManyField(related_name='evenements', to='presence.Etudiant'),
        ),
    ]
