# Generated by Django 3.0 on 2019-12-19 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0008_tempimage_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TempImage',
        ),
    ]
