# Generated by Django 3.0 on 2019-12-19 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0009_delete_tempimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individu',
            old_name='faceId',
            new_name='face_id',
        ),
    ]
