# Generated by Django 3.0 on 2019-12-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0010_auto_20191219_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='groupe_participant',
            field=models.ManyToManyField(related_name='evenements', to='presence.GroupeParticipant'),
        ),
    ]
