# Generated by Django 3.0 on 2019-12-30 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0011_auto_20191230_1809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evenement',
            old_name='etudiants',
            new_name='presences',
        ),
    ]
