# Generated by Django 3.0 on 2019-12-26 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0012_auto_20191226_0027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evenement',
            old_name='groupe_participant',
            new_name='groupe_participants',
        ),
    ]
