# Generated by Django 3.0 on 2020-01-03 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0013_auto_20191226_0029'),
        ('presence', '0012_auto_20191230_1811'),
    ]

    operations = [
    ]
