# Generated by Django 3.0 on 2020-01-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0014_merge_20200104_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='presences',
            field=models.ManyToManyField(blank=True, null=True, related_name='evenements', to='presence.Etudiant'),
        ),
    ]
