# Generated by Django 3.0 on 2020-01-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0015_auto_20200104_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='presences',
            field=models.ManyToManyField(blank=True, related_name='evenements', to='presence.Etudiant'),
        ),
    ]
