# Generated by Django 3.0 on 2020-01-07 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0014_merge_20200104_0000'),
        ('presence', '0016_auto_20200104_1546'),
    ]

    operations = [
    ]
