# Generated by Django 3.0 on 2020-01-09 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0017_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
