# Generated by Django 3.0 on 2020-01-10 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0018_delete_photo'),
        ('presence', '0017_merge_20200107_1731'),
    ]

    operations = [
    ]
