# Generated by Django 3.0 on 2020-02-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0019_merge_20200110_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsable',
            name='password',
            field=models.CharField(default='password', max_length=255),
            preserve_default=False,
        ),
    ]
